### PR TITLE
Bolatito added her portion of the project

### PR DESCRIPTION
**Pull request by EtechAppGroup2**
Engr. Tunde / Engr. Chris, 

kindly review before this is merged.

Thank you .

### CODE REVIEW

**Review by evaino12 — APPROVED** [review]
This is approved and aligns with set objective.

**Comment by DevBizGuy** [comment]
Stages 3 and 4 have the same name, they should have unique names. Please update.

**Review by EtechAppGroup2 — COMMENTED** [review]
Good Morning Engr. Chris, 
There is a slight difference in the name. Stage 3 and Stage 4 respectively.
The Instructor wants to see the names of each person on the process written by him or her.
It was deliberate because that is what the question says.
Thank you.

**Comment by EtechAppGroup2** [comment]
Thank you Engr. Tunde.
I appreciate your response.

**Comment by DevBizGuy** [comment]
Ok, noted.

**Pull request merged**
